In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [8,9,11],
             [56,89,90]])
a.shape

(4, 3)

In [4]:
a = np.array([1, 2, 3, 4, 5, 6, 7,33,78,97])
a

array([ 1,  2,  3,  4,  5,  6,  7, 33, 78, 97])

In [5]:
a[0]

np.int64(1)

In [6]:
a[9] = 1000
a

array([   1,    2,    3,    4,    5,    6,    7,   33,   78, 1000])

In [7]:
a[:8]

array([ 1,  2,  3,  4,  5,  6,  7, 33])

In [8]:
b = a[3:]
b

array([   4,    5,    6,    7,   33,   78, 1000])

In [9]:
b[0] = 40
a

array([   1,    2,    3,   40,    5,    6,    7,   33,   78, 1000])

In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a[1, 3]

np.int64(8)

In [12]:
a.ndim

2

In [13]:
a.shape

(3, 4)

In [14]:
a.size

12

In [15]:
import math
a.size == math.prod(a.shape)

True

In [16]:
a.dtype

dtype('int64')

In [17]:
a.dtype

dtype('int64')

In [18]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.empty(2)

array([-1.29393662e-104, -2.97926417e+251])

In [21]:
np.empty(3) 

array([3., 2., 1.])

In [22]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.arange(2, 80, 6)

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74])

In [24]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
x = np.ones(6, dtype=np.int64)
x

array([1, 1, 1, 1, 1, 1])

In [26]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [27]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [29]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [31]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]],
                          
                          [[6, 7, 8, 9],
                          [2, 4, 7, 9]]])

In [33]:
array_example.ndim
array_example.size

32

In [34]:
array_example.shape

(4, 2, 4)

In [35]:
array_example = np.array([[[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]]])

In [36]:
array_example.ndim

4

In [37]:
array_example.shape

(1, 2, 2, 4)

In [38]:
array_example.size

16

In [39]:
arr = np.array([[[1, 2], 
                  [3, 4], 
                  [5, 6], 
                  [7, 8]]])
print(arr.ndim)

3


In [40]:
array_example.shape

(1, 2, 2, 4)

In [41]:
array_example.ndim

4

In [42]:
array_example.size

16

In [43]:
array_example.shape

(1, 2, 2, 4)

In [44]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [45]:
b = a.reshape(4, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [46]:
np.reshape(a, shape=(1, 8), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [47]:
a = np.array([1, 2, 3, 4, 5, 6,7,8])
a.shape

(8,)

In [48]:
a2 = a[np.newaxis, :]
a2.shape

(1, 8)

In [49]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 8)

In [50]:
col_vector = a[:, np.newaxis]
col_vector.shape

(8, 1)

In [51]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [52]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [53]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [54]:
data = np.array([1, 2, 3])

In [55]:
data[1]

np.int64(2)

In [56]:
data[0:2]

array([1, 2])

In [57]:
data[1:]

array([2, 3])

In [58]:
data[-2:]

array([2, 3])

In [59]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [60]:
print(a[a < 5])

[1 2 3 4]


In [61]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [62]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [63]:
c = a[(a > 5) & (a < 11)]
print(c)

[ 6  7  8  9 10]


In [64]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [65]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [66]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [67]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [68]:
print(a[b])

[1 2 3 4]


In [69]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [71]:
np.power(100, 9, dtype=np.int64)

np.int64(1000000000000000000)

In [72]:
np.power(100, 9, dtype=np.int32)

np.int32(-1486618624)

In [73]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [76]:
import numpy as np
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [78]:
import numpy as np
x = np.arange(10)
x
y = x[1:3]  # creates a view
y
x[1:3] = [10, 11]
x
y

array([10, 11])

In [80]:
import numpy as np
x = np.arange(9)
x
y = x.reshape(3, 3)
y
y.base  # .reshape() creates a view
z = y[[2, 1]]
z
z.base is None  # advanced indexing creates a copy

True