In [38]:
import numpy as np

In [39]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [8,9,11],
             [56,89,90]])
a.shape

(4, 3)

In [40]:
a = np.array([1, 2, 3, 4, 5, 6, 7,33,78,97])
a

array([ 1,  2,  3,  4,  5,  6,  7, 33, 78, 97])

In [41]:
a[0]

np.int64(1)

In [42]:
a[9] = 1000
a

array([   1,    2,    3,    4,    5,    6,    7,   33,   78, 1000])

In [43]:
a[:8]

array([ 1,  2,  3,  4,  5,  6,  7, 33])

In [44]:
b = a[3:]
b

array([   4,    5,    6,    7,   33,   78, 1000])

In [45]:
b[0] = 40
a

array([   1,    2,    3,   40,    5,    6,    7,   33,   78, 1000])

In [46]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
a[1, 3]

np.int64(8)

In [48]:
a.ndim

2

In [49]:
a.shape

(3, 4)

In [50]:
a.size

12

In [51]:
import math
a.size == math.prod(a.shape)

True

In [52]:
a.dtype

dtype('int64')

In [53]:
a.dtype

dtype('int64')

In [55]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [57]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.empty(2)

array([1., 1.])

In [61]:
np.empty(3) 

array([3., 2., 1.])

In [63]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
np.arange(2, 80, 6)

array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56, 62, 68, 74])

In [69]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [75]:
x = np.ones(6, dtype=np.int64)
x

array([1, 1, 1, 1, 1, 1])

In [76]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [77]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [79]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [84]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [110]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]],
                          
                          [[6, 7, 8, 9],
                          [2, 4, 7, 9]]])

In [111]:
array_example.ndim
array_example.size

32

In [112]:
array_example.shape

(4, 2, 4)

In [125]:
array_example = np.array([[[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]]])

In [126]:
array_example.ndim

4

In [127]:
array_example.shape

(1, 2, 2, 4)

In [128]:
array_example.size

16

In [129]:
arr = np.array([[[1, 2], 
                  [3, 4], 
                  [5, 6], 
                  [7, 8]]])
print(arr.ndim)

3


In [130]:
array_example.shape

(1, 2, 2, 4)

In [131]:
array_example.ndim

4

In [132]:
array_example.size

16

In [133]:
array_example.shape

(1, 2, 2, 4)

In [144]:
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [146]:
b = a.reshape(4, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [148]:
np.reshape(a, shape=(1, 8), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [153]:
a = np.array([1, 2, 3, 4, 5, 6,7,8])
a.shape

(8,)

In [154]:
a2 = a[np.newaxis, :]
a2.shape

(1, 8)

In [155]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 8)

In [157]:
col_vector = a[:, np.newaxis]
col_vector.shape

(8, 1)

In [158]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [159]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [160]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [161]:
data = np.array([1, 2, 3])

In [162]:
data[1]

np.int64(2)

In [163]:
data[0:2]

array([1, 2])

In [164]:
data[1:]

array([2, 3])

In [165]:
data[-2:]

array([2, 3])

In [166]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [167]:
print(a[a < 5])

[1 2 3 4]


In [168]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [169]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [171]:
c = a[(a > 5) & (a < 11)]
print(c)

[ 6  7  8  9 10]


In [172]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [173]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [174]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [175]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [176]:
print(a[b])

[1 2 3 4]


In [179]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))
